name: jo_sequal_task
description: this is wallpaper app  responsible for render images from an api the app have  many screen home screen for the whole and search screen for finding image and favorite screen for favorite image



publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.2
  dio: ^5.0.3
  cached_network_image: ^3.2.3
  hooks_riverpod: ^2.3.2
  auto_route: ^5.0.2
  flutter_screenutil: ^5.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_hooks: ^0.18.6
  path_provider: ^2.0.13
  infinite_scroll_pagination: ^3.2.0
  hive_generator: ^2.0.0
  freezed_annotation:
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  intl: ^0.18.0
  image_downloader:
  path: ^1.8.2
  sqflite: ^2.2.6

dev_dependencies:
  flutter_launcher_icons: ^0.12.0
  flutter_test:
    sdk: flutter
  auto_route_generator: ^5.0.3


  
  
  
  
  
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/appIcon.png"
  min_sdk_android: 21 # 





flutter:

  
  
  
  uses-material-design: true
  assets:
    - assets/images/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
